
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-login
  template:
    metadata:
      labels:
        app: backend-login
    spec:
      containers:
        - name: backend-login
          image: your-dockerhub-username/quiz-backend-login:latest
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: backend-login-service
spec:
  selector:
    app: backend-login
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-marks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-marks
  template:
    metadata:
      labels:
        app: backend-marks
    spec:
      containers:
        - name: backend-marks
          image: your-dockerhub-username/quiz-backend-marks:latest
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: backend-marks-service
spec:
  selector:
    app: backend-marks
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/quiz-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
