# deployment.yaml

# Backend Login Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-login
  template:
    metadata:
      labels:
        app: backend-login
    spec:
      containers:
        - name: backend-login
          image: nithi1230/quiz-backend-login:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: backend-login-service
spec:
  selector:
    app: backend-login
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP

# Backend Marks Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-marks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-marks
  template:
    metadata:
      labels:
        app: backend-marks
    spec:
      containers:
        - name: backend-marks
          image: nithi1230/quiz-backend-marks:latest
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: backend-marks-service
spec:
  selector:
    app: backend-marks
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP

# Frontend Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nithi1230/quiz-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
